### ISSUE TITLE
建议您不要定义自己的样式

### ISSUE THREAD

**Issue by bcw104** [BE-FE/iToolkit#32]
如题，最好是围绕bootstrap来做，这样的话您会获得大量的用户和支持。现在的样式跟bootstrap不兼容。好多tag很实用，本来打算直接用的，后来只能扒下来自己改写了。一直想找一个能封装bootstrap的riot tag库。

**Comment by xieyu33333** [comment]
后续会以皮肤的方式添加Bootstrap支持

**Comment by xieyu33333** [comment]
新版本样式已添加命名空间，和BS不会冲突
